ManagedObjects : CSV Informational Reports
facebookresearch/habitat-sim pull request #1331
Opened 2021-06-21 20:13 UTC by jturner65

## Motivation and Context
This PR introduces reporting functionality for loaded attributes and wrappers from their respective managers, and the Metadata Mediator.  Functions are provided that will construct csv-friendly strings of data from each attributes and managed object, and lists of these strings for each manager.  The MetadaMediator can be queried to provide an aggregate report of all loaded configurations. 

This functionality is of particular importance with upcoming MetadataMediator/SceneDataset/SceneInstance Documentation and Tutorials. 

To be finished : 
- Simple python function that will take the result and write it to a file of the user's choosing. 
- Slight refactor of attributes to take advantage of new Magnum Configuration key-querying.

## How Has This Been Tested
C++ and python tests pass. The MetadataMediator test has been expanded to test this functionality, although currently it just displays a report.  AttributesManagerTest will also be modified to test this functionality.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-06-21 20:27 UTC, Skylion007 commented on src/esp/metadata/MetadataMediator.cpp
> +    res += sceneDatasetAttributesManager_->getObjectByHandle(handle)
clang-tidy is not going to like this. Consider stringbuilding

2021-06-21 20:32 UTC, Skylion007 approved these changes

2021-06-21 20:32 UTC, Skylion007 commented on src/esp/metadata/attributes/AttributesBase.h
> +  for (const auto& it : ShaderTypeNamesMap) {
We really may want to invest in a bimap implementation

2021-06-21 20:32 UTC, Skylion007 commented on src/esp/metadata/attributes/LightLayoutAttributes.cpp
> +      res += "," + lightInst.second->getObjectInfoHeader();
String building

2021-06-21 20:32 UTC, Skylion007 commented on src/esp/metadata/attributes/SceneAttributes.cpp
> +  return cfg.value("translation") + ", " + cfg.value("rotation") + ", " +
https://clang.llvm.org/extra/clang-tidy/checks/performance-inefficient-string-concatenation.html

2021-06-21 20:32 UTC, Skylion007 commented
The biggest issue here is that the string are not built efficiently. See https://clang.llvm.org/extra/clang-tidy/checks/performance-inefficient-string-concatenation.html

2021-06-21 20:32 UTC, Skylion007 requested changes
https://clang.llvm.org/extra/clang-tidy/checks/performance-inefficient-string-concatenation.html

2021-06-22 12:12 UTC, jturner65 commented on src/esp/metadata/attributes/LightLayoutAttributes.cpp
> +      res += "," + lightInst.second->getObjectInfoHeader();
[+= calls append.](https://timsong-cpp.github.io/cppwp/n3337/string::op+=#1)

2021-06-22 14:14 UTC, Skylion007 commented on src/esp/metadata/MetadataMediator.cpp
> +      attributes::SceneDatasetAttributes::getDatasetSummaryHeader() + "\n";
Nit shouldn't these newlines be chars? (Single quotes)?

2021-06-22 14:16 UTC, Skylion007 commented on src/esp/metadata/attributes/LightLayoutAttributes.cpp
> +    res.append(", ").append(lightInst.second->getObjectInfo()).append("\n");
Again here (pretty sure there is a more efficient overload for appending chars.

2021-06-22 14:17 UTC, Skylion007 commented on src/esp/metadata/attributes/SceneDatasetAttributes.cpp
> +  for (const std::string& s : stageAttrInfoAra) {
here again

2021-06-22 14:19 UTC, Skylion007 requested changes
Chars overloads

2021-06-22 15:21 UTC, Skylion007 commented on src/esp/metadata/MetadataMediator.cpp
> +           "\n";
```suggestion
           "\n";
```
```suggestion
    res += sceneDatasetAttributesManager_->getObjectByHandle(handle)
               ->getDatasetSummary();
    res += "\n";
```

2021-06-22 15:24 UTC, Skylion007 commented on src/esp/metadata/attributes/LightLayoutAttributes.cpp
> +      res.append(1, ',')
BTW res+= for every item is also viable here.

2021-06-22 15:25 UTC, Skylion007 approved these changes

2021-06-22 17:34 UTC, jturner65 commented
Here's an example report generated on the AI2Thor scene instances I generated a few months ago, to give an idea of what this will look like.
[ai2thor_first_report.csv](https://github.com/facebookresearch/habitat-sim/files/6696297/ai2thor_first_report.csv)

2021-06-22 23:17 UTC, merged