Updated the Habitat 2.0 citation
facebookresearch/habitat-sim pull request #1354
Opened 2021-06-29 22:30 UTC by ASzot

## Motivation and Context

The recently released Habitat 2.0 paper needs to be in the references and citations list.

## How Has This Been Tested

Visually inspected rendered README.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-06-29 22:32 UTC, aclegg3 approved these changes

2021-06-29 22:33 UTC, mathfac approved these changes
🚀🚀🚀

2021-06-29 22:34 UTC, dhruvbatra commented
@ASzot -- let's also add the bibtex to the "Citing Habitat" section.

2021-06-30 00:51 UTC, ASzot commented
Now added.

2021-06-30 01:34 UTC, Skylion007 commented
Same comment as Hab-Lab. I personallly would prefer the newer citation first. Thoughts?

2021-06-30 01:35 UTC, Skylion007 requested changes
Same comment as before.

2021-06-30 01:38 UTC, Skylion007 commented on README.md
> +@article{szot2021habitat,
Consider moving this bibtex to the top.

2021-06-30 04:51 UTC, aclegg3 commented
CI doesn't like this PR. 🤷

2021-06-30 04:51 UTC, closed without merging