[WIP] Build OSX Conda Nightly
facebookresearch/habitat-sim pull request #1430
Opened 2021-08-06 18:57 UTC by Skylion007

## Motivation and Context
* Build Nightly OSX Binaries
@mathfac Putting this here so I can get some help testing and deploying the CI command.

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-08-12 22:23 UTC, mathfac requested changes
Ideally the one job should serve 3 use-cases:
- CI test build with limited python versions support without upload that will run on every commit
- CI nightly that will build nightly package from master and upload it
- Version release that will build the packages and upload it to main Habitat conda channel.

2021-08-12 22:23 UTC, mathfac commented on .circleci/config.yml
> +    parameters:
It's better to have same parameter signature like [the linux building job](https://github.com/facebookresearch/habitat-sim/blob/f216a1732a2d33747c56df9a4d07485ba70cda3a/.circleci/config.yml#L617-L626):

```
    parameters:
      AIHABITAT_CONDA_CHN:
        type: string
        default: "aihabitat"
      AIHABITAT_CONDA_CHN_PWD_VAR:
        type: string
        default: "AIHABITAT_CONDA_PWD"
      NIGHTLY_FLAG:
        type: string
        default: ""
```
 Maybe, add one more parameter `upload` for cases when no upload required.

2021-08-12 22:23 UTC, mathfac commented on .circleci/config.yml
> +            <<^ parameters.test>> anaconda login --username $AIHABITAT_CONDA_CHN --password $AIHABITAT_CONDA_CHN_PWD
Here channel is known and nonsensitive information, while password is taken from environment variable and parameter is used only for the variable name:

```suggestion
            anaconda login --username << parameters.AIHABITAT_CONDA_CHN >>  --password $<< parameters.AIHABITAT_CONDA_CHN_PWD_VAR >>
```

2021-08-12 22:41 UTC, mathfac commented
The error you have right now is not related to the anaconda, but pre installed dependencies:
`cp: cannot stat '/usr/include/EGL': No such file or directory`

2021-11-03 20:03 UTC, erikwijmans commented
> @erikwijmans The conda nightly builds are currently being built, after they are done I will add them as a dependency on build_conda_binaries so they are run if the Linux conda build succeeds.

I guess the dependency is since the linux one is responsible for removing old binaries? If so, we can factor that out in the future, but no need to do that now.

2021-11-03 20:22 UTC, Skylion007 commented
Exactly

> 
> 
> > @erikwijmans The conda nightly builds are currently being built, after they are done I will add them as a dependency on build_conda_binaries so they are run if the Linux conda build succeeds.
> 
> I guess the dependency is since the linux one is responsible for removing old binaries? If so, we can factor that out in the future, but no need to do that now.

Exactly

2021-11-03 21:01 UTC, erikwijmans approved these changes
Ship it!

2021-11-04 01:28 UTC, merged