Modify ResourceManager::loadStage to consume MM instead of arguments.
facebookresearch/habitat-sim pull request #1436
Opened 2021-08-12 16:57 UTC by jturner65

## Motivation and Context
This small PR changes the argument list for loadStage to remove createSemanticMesh and forceSeparateSemanticSceneGraph, and instead query the MetadataMediator's copy of simConfig for these values, which is always synched with Simulator and always the most relevant/pertinent simConfig whenever a scene's assets are loaded. 

## How Has This Been Tested
Local C++ and python tests.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-08-12 19:05 UTC, Skylion007 approved these changes

2021-08-12 19:06 UTC, Skylion007 requested changes
```habitat-sim/src/tests/ResourceManagerTest.cpp:122:73: error: no matching function for call to ‘esp::assets::ResourceManager::loadStage(std::shared_ptr<esp::metadata::attributes::StageAttributes>&, std::nullptr_t, esp::scene::SceneManager*, std::vector<int>&, bool)’
                                           &sceneManager_, tempIDs, false);``` Need to change there as well. Make sure all tests build.

2021-08-12 21:13 UTC, jturner65 commented
> ```
> habitat-sim/src/tests/ResourceManagerTest.cpp:122:73: error: no matching function for call to ‘esp::assets::ResourceManager::loadStage(std::shared_ptr<esp::metadata::attributes::StageAttributes>&, std::nullptr_t, esp::scene::SceneManager*, std::vector<int>&, bool)’
>                                            &sceneManager_, tempIDs, false);
> ```
> 
> Need to change there as well. Make sure all tests build.

Ah, missed that one, is in a VHACD test

2021-08-13 16:42 UTC, aclegg3 approved these changes

2021-08-13 20:15 UTC, Skylion007 approved these changes

2021-08-13 20:18 UTC, merged