[docs] README conda install
facebookresearch/habitat-sim pull request #789
Opened 2020-09-11 23:14 UTC by aclegg3

## Motivation and Context

Introducing conda install on this release, so tell new users how to use this for install.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-09-11 23:15 UTC, Skylion007 commented
@aclegg3 How is this different from #588 ?

2020-09-11 23:26 UTC, aclegg3 commented
> @aclegg3 How is this different from #588 ?

Thanks, didn't realize this was open and waiting. Thanks for linking. We didn't have nightly build yet, so we were waiting. 🤷

2020-09-12 00:26 UTC, erikwijmans requested changes

2020-09-12 00:26 UTC, erikwijmans commented on README.md
> +We provide conda packages for [the most recent release](https://anaconda.org/aihabitat) and built [nightly for the master branch](https://anaconda.org/aihabitat-nightly). Packages are provided for st
```suggestion
We provide conda packages for [the most recent release](https://anaconda.org/aihabitat) and built [nightly for the master branch](https://anaconda.org/aihabitat-nightly). Packages are provided for standard and headless systems with and without Bullet physics support. When possible, we suggest this method of installation for the most simple and straight-forward installation experience.
```

That readme is just for building habitat sim's conda package. 99% of users don't need to read it.

2020-09-12 00:26 UTC, erikwijmans commented on README.md
> +conda install -c aihabitat-nightly withbullet
To install habitat-sim on systems with an attached display:
```
conda install habitat-sim  -c conda-forge -c aihabitat
```

To install the headless build of habitat sim
```
conda install habitat-sim headless -c conda-forge -c aihabitat
```

To install habitat-sim with bullet physics [on a headless system]
```
conda install habitat-sim withbullet [headless] -c conda-forge -c aihabitat
```

To get the nightly build of latest master, simply swap `-c aihabitat` for `-c aihabitat-nightly`

2020-09-13 00:42 UTC, dhruvbatra approved these changes

2020-09-13 15:05 UTC, erikwijmans approved these changes

2020-09-13 15:06 UTC, Skylion007 approved these changes

2020-09-14 16:04 UTC, merged