[bugfix] Better handling for MotionType::KINEMATIC
facebookresearch/habitat-sim pull request #802
Opened 2020-09-15 22:45 UTC by aclegg3

## Motivation and Context

Noticed that `MotionType::KINEMATIC` objects were not responding correctly in many cases. Investigation led to this refactor. We need to create a new `btRigidObject` with different properties when swapping between `KINEMATIC` and `DYNAMIC` `MotionTypes`.

## How Has This Been Tested

Current tests pass.
Local testing in viewer for identified edge case:

**Before:**
Notice the sleeping object's collision shape is out of sync after set to kinematic.
Notice the skating of dynamic objects when stacking on a kinematic object.
![before_kinematic_fix](https://user-images.githubusercontent.com/1445143/93272318-0fafe080-f76a-11ea-838d-c6676bde708d.gif)

**After:**
These issues are fixed. Notice objects in contact with kinematic objects will not sleep.
![after_kinematic_fix](https://user-images.githubusercontent.com/1445143/93272329-163e5800-f76a-11ea-8d6e-12c5abc5bdd0.gif)

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-09-15 23:07 UTC, Skylion007 approved these changes

2020-09-15 23:08 UTC, Skylion007 commented
if it builds and fixes the issue. ship it.

2020-09-15 23:08 UTC, Skylion007 requested changes
Seems to be failing physics tests.

2020-09-16 00:54 UTC, aclegg3 commented
> Seems to be failing physics tests.

Yeah, found an inertia bug. (yay tests!)

Also needed to adjust a golden number for another test. The accuracy of simulation actually improved here: a dynamic object supported by a moving kinematic object sticks better now.

2020-09-16 13:04 UTC, Skylion007 approved these changes

2020-09-16 15:30 UTC, merged